name: CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./mvnw --batch-mode verify
